version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging into docker
      - awsAccountID=$(aws sts get-caller-identity --query "Account" --output text)
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${awsAccountID}.dkr.ecr.us-east-1.amazonaws.com
      - echo Cloud Formation
      - aws cloudformation deploy --template-file cloudformation.yml --stack-name Blinky-Backend --capabilities CAPABILITY_NAMED_IAM
  build:
    commands:
      - echo Building Docker Image
      - repoURI=$(aws cloudformation describe-stacks --query "Stacks[?StackName=='Blinky-Backend'][].Outputs[?OutputKey=='RepoURI'].OutputValue" --output text)
      - docker build -t 836428984343.dkr.ecr.us-east-1.amazonaws.com/blinky-backend:latest .
      - docker push 836428984343.dkr.ecr.us-east-1.amazonaws.com/blinky-backend:latest
