version: 0.2

phases:
  pre_build:
    commands:
      - echo Cloud Formation
      - aws cloudformation deploy --template-file cloudformation.yml --stack-name Blinky-Backend
  build:
    commands:
      - echo Building Docker Image
      - repoURI=$(aws cloudformation describe-stacks --query "Stacks[?StackName=='Blinky-Backend'][].Outputs[?OutputKey=='RepoURI'].OutputValue" --output text)
      - awsAccountID=${aws sts get-caller-identity --query "Account" --output text}
      - awsRegion=${aws configure get region}
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${awsAccountID}.dkr.ecr.${awsRegion}.amazonaws.com
      - docker build -t ${repoURI}:latest .
      - docker push ${repoURI}:latest
