# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  blinkybackend:
    image: blinkybackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 33060:33060
      - 3306:3306
